// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com


tinyMCE.addToLang('',{
theme_style_select : '-- 式樣 --',
theme_code_desc : '編輯HTML源代碼',
theme_code_title : 'HTML源代碼編輯器',
theme_code_wordwrap : '自動換行',
theme_sub_desc : '下標',
theme_sup_desc : '上標',
theme_hr_desc : '插入水平線',
theme_custom1_desc : '這裡填寫用戶自定義描述',
theme_removeformat_desc : '移除格式',
insert_image_border : '邊框',
insert_image_dimensions : '維數',
insert_image_vspace : '垂直間距',
insert_image_hspace : '水平間距',
insert_image_align : '對齊方式',
insert_image_align_default : '-- 默認 --',
insert_image_align_baseline : '基線',
insert_image_align_top : '頂端',
insert_image_align_middle : '居中',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字上方',
insert_image_align_absmiddle : '絕對居中',
insert_image_align_absbottom : '絕對底部',
insert_image_align_left : '左對齊',
insert_image_align_right : '右對齊',
theme_font_size : '-- 字號 --',
theme_fontdefault : '-- 字體 --',
theme_block : '-- 格式 --',
theme_paragraph : '段落',
theme_div : '層',
theme_address : '地址',
theme_pre : '預格式化',
theme_h1 : '標題 1',
theme_h2 : '標題 2',
theme_h3 : '標題 3',
theme_h4 : '標題 4',
theme_h5 : '標題 5',
theme_h6 : '標題 6',
theme_blockquote : '引用',
theme_code : '代碼',
theme_samp : '代碼模板',
theme_dt : '定義期限 ',
theme_dd : '定義內容',
theme_colorpicker_title : '選擇顏色',
theme_colorpicker_apply : '應用',
theme_forecolor_desc : '選擇文字顏色',
theme_backcolor_desc : '選擇背景顏色',
theme_charmap_title : '選擇特殊符號',
theme_charmap_desc : '插入特殊符號',
theme_visualaid_desc : '開關不可見元素',
insert_anchor_title : '插入/編輯 錨點',
insert_anchor_name : '錨點名稱',
theme_anchor_desc : '插入/編輯 錨點',
theme_insert_link_titlefield : '標題',
theme_clipboard_msg : '剪切/複製/粘貼功能在 Mozilla 和 Firefox 瀏覽器中不支持。\n您希望獲得更多的信息嗎？',
cut_desc : '剪切',
copy_desc : '複製',
paste_desc : '粘貼',
theme_path : '路徑',
newdocument_desc : '新建文檔',
newdocument : '您確認要清除所有內容嗎？',
link_list : '鏈接列表',
image_list : '圖像列表',
browse : '瀏覽',
image_props_desc : '圖像屬性',
class_name : '類',
about_title : '關於 TinyMCE',
about : '關於',
license : '授權書',
plugins : '所有插件',
plugin : '插件',
author : '作者',
version : '版本',
loaded_plugins : '讀取插件',
help : '幫助',
not_set : '-- 空設定 --',
close : '關閉',
toolbar_focus : '跳到工具按鈕 - Alt+Q, 跳到編輯器 - Alt-Z, 跳到元素路徑 - Alt-X'
});
